apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
metadata:
  creationTimestamp: null
  name: org2-peer0
  namespace: default
spec:
  affinity: null
  couchDBexporter: null
  couchdb:
    externalCouchDB: null
    image: couchdb
    password: couchdb
    pullPolicy: ""
    tag: 3.1.1
    user: couchdb
  deliveryClientaddressOverrides: null
  discovery:
    period: 60s
    touchPeriod: 60s
  dockerSocketPath: ""
  env: null
  external_chaincode_builder: false
  externalBuilders:
  - name: ccaas_builder
    path: /opt/hyperledger/ccaas_builder
    propagateEnvironment:
    - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG
  externalEndpoint: peer0-org2.workshop.adityajoshi.online:443
  fsServer: null
  gatewayApi:
    gatewayName: hlf-gateway
    gatewayNamespace: default
    port: 443
  gossip:
    aliveExpirationTimeout: ""
    aliveTimeInterval: ""
    bootstrap: ""
    endpoint: ""
    externalEndpoint: peer0-org2.workshop.adityajoshi.online:443
    orgLeader: true
    reconnectInterval: ""
    responseWaitTime: ""
    useLeaderElection: false
  grpcProxy: null
  hostAliases: null
  hosts:
  - peer0-org2.workshop.adityajoshi.online
  image: hyperledger/fabric-peer
  imagePullPolicy: Always
  imagePullSecrets: null
  istio:
    hosts:
    - peer0-org2.workshop.adityajoshi.online
    ingressGateway: ingressgateway
    port: 443
  logging:
    cauthdsl: info
    gossip: info
    grpc: info
    ledger: info
    level: info
    msp: info
    peer: info
    policies: info
  mspID: Org2MSP
  peerVolumeMounts: null
  podAnnotations: null
  podLabels: null
  replicas: 1
  resources:
    chaincode:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10m
    couchdb:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 10m
    couchdbExporter: null
    peer:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
    proxy: null
  secret:
    enrollment:
      component:
        cahost: org2-ca.workshop.adityajoshi.online
        caname: ca
        caport: 443
        catls:
          cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNjVENDQWhpZ0F3SUJBZ0lRUE53T0h6eFN0UjU2YWxQMmx0QktaREFLQmdncWhrak9QUVFEQWpCU01STXcKRVFZRFZRUUdFd3BEWVd4cFptOXlibWxoTVFrd0J3WURWUVFIRXdBeENUQUhCZ05WQkFrVEFERVVNQklHQTFVRQpDaE1MU0hsd1pYSnNaV1JuWlhJeER6QU5CZ05WQkFzVEJrWmhZbkpwWXpBZUZ3MHlOREExTVRReE9EVXdNRFZhCkZ3MHpOREExTVRVeE9EVXdNRFZhTUZJeEV6QVJCZ05WQkFZVENrTmhiR2xtYjNKdWFXRXhDVEFIQmdOVkJBY1QKQURFSk1BY0dBMVVFQ1JNQU1SUXdFZ1lEVlFRS0V3dEllWEJsY214bFpHZGxjakVQTUEwR0ExVUVDeE1HUm1GaQpjbWxqTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcjlUNGhjZjZKTS9YelpaUkRHRm10ek5DCmNoZSs0a0dHRjJLK2JVcTJOckI0SGgxemJvemlQSlpIWVdMZ3FOTFpCMlNDd05tMWhMOXBXbkRkUFNpVTJhT0IKenpDQnpEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRgpCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3S1FZRFZSME9CQ0lFSURmcmNpWjdLSVpkN2dMUmFMVkJFRURjCmZiU1RsaUNBVkdya2txY3A4TFBiTUY4R0ExVWRFUVJZTUZhQ0NXeHZZMkZzYUc5emRJSUhiM0puTWkxallZSVAKYjNKbk1pMWpZUzVrWldaaGRXeDBnaU52Y21jeUxXTmhMbmR2Y210emFHOXdMbUZrYVhSNVlXcHZjMmhwTG05dQpiR2x1WlljRWZ3QUFBWWNFajI3NmNqQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQWRNeFNZTlltcTNqUWUvREo4CnJRRnBBUC95aGY5aGNyVVpGRWNpTC9aUEx3SWdFSE82aCsvTGRnQmxNOGxIUFpEVVJMb0E5TEpyMVVIMzRVREsKUkdCbjhFQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          secretRef: null
        enrollid: peer
        enrollsecret: peerpw
        external: null
      tls:
        cahost: org2-ca.workshop.adityajoshi.online
        caname: tlsca
        caport: 443
        catls:
          cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNjVENDQWhpZ0F3SUJBZ0lRUE53T0h6eFN0UjU2YWxQMmx0QktaREFLQmdncWhrak9QUVFEQWpCU01STXcKRVFZRFZRUUdFd3BEWVd4cFptOXlibWxoTVFrd0J3WURWUVFIRXdBeENUQUhCZ05WQkFrVEFERVVNQklHQTFVRQpDaE1MU0hsd1pYSnNaV1JuWlhJeER6QU5CZ05WQkFzVEJrWmhZbkpwWXpBZUZ3MHlOREExTVRReE9EVXdNRFZhCkZ3MHpOREExTVRVeE9EVXdNRFZhTUZJeEV6QVJCZ05WQkFZVENrTmhiR2xtYjNKdWFXRXhDVEFIQmdOVkJBY1QKQURFSk1BY0dBMVVFQ1JNQU1SUXdFZ1lEVlFRS0V3dEllWEJsY214bFpHZGxjakVQTUEwR0ExVUVDeE1HUm1GaQpjbWxqTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcjlUNGhjZjZKTS9YelpaUkRHRm10ek5DCmNoZSs0a0dHRjJLK2JVcTJOckI0SGgxemJvemlQSlpIWVdMZ3FOTFpCMlNDd05tMWhMOXBXbkRkUFNpVTJhT0IKenpDQnpEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRgpCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3S1FZRFZSME9CQ0lFSURmcmNpWjdLSVpkN2dMUmFMVkJFRURjCmZiU1RsaUNBVkdya2txY3A4TFBiTUY4R0ExVWRFUVJZTUZhQ0NXeHZZMkZzYUc5emRJSUhiM0puTWkxallZSVAKYjNKbk1pMWpZUzVrWldaaGRXeDBnaU52Y21jeUxXTmhMbmR2Y210emFHOXdMbUZrYVhSNVlXcHZjMmhwTG05dQpiR2x1WlljRWZ3QUFBWWNFajI3NmNqQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQWRNeFNZTlltcTNqUWUvREo4CnJRRnBBUC95aGY5aGNyVVpGRWNpTC9aUEx3SWdFSE82aCsvTGRnQmxNOGxIUFpEVVJMb0E5TEpyMVVIMzRVREsKUkdCbjhFQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          secretRef: null
        csr:
          cn: ""
          hosts:
          - 127.0.0.1
          - localhost
          - 143.110.250.114
          - 143.110.246.70
          - 143.110.250.221
          - org2-peer0
          - org2-peer0.default
          - peer0-org2.workshop.adityajoshi.online
        enrollid: peer
        enrollsecret: peerpw
        external: null
  service:
    type: ClusterIP
  serviceMonitor: null
  stateDb: couchdb
  storage:
    chaincode:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: do-block-storage
    couchdb:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: do-block-storage
    peer:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: do-block-storage
  tag: 2.4.6
  tolerations: null
  traefik: null
  updateCertificateTime: null
  volumes: null

